### ISSUE TITLE
remove last block on 3node page

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_threefold_farming#102]
![Screenshot 2021-06-01 at 19 25 17](https://user-images.githubusercontent.com/54844940/120349565-45ecba80-c30f-11eb-8611-8f60821e166d.png)

https://threefold.io/farming/get_3node

Add button instead > Pre-register for our next batch 
link > https://threefold.io/farming/pre-register

**Comment by Vilnite** [comment]
Need to put this back on Pre-Register page.
Was asked to remove only from get_3node page.

**Comment by Sacha96** [comment]
The block was removed on 3node page which is good. 

But it was also removed from pre register page. Lets bring it back as last block in page. if not sure please pm me.
