### ISSUE TITLE
Add button for markdown

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_farming#11]
Please code a button for markdown.
Sam as we have for card component:
![button](https://user-images.githubusercontent.com/20182572/101771304-02488f00-3aea-11eb-88a4-19b9e7328325.png)

**Comment by Vilnite** [comment]
@samaradel where can I find it? see it?

**Comment by samaradel** [comment]
just fill ```button``` and ```link```  with data

![image](https://user-images.githubusercontent.com/11662805/102008614-9446d680-3d3a-11eb-87c4-94563fa3edac.png)
