### ISSUE TITLE
Improve linking to Farming Wiki

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_threefold_farming#113]
Kristof identified a lack of links to the farming wiki from the current structure.

- [x] Improve the user journey so the Wiki is found more easily.

- [x] QA with @Sacha96

**Comment by Vilnite** [comment]
To properly link to Farming sections in wiki we need to improve it first.
Suggested changes: https://github.com/threefoldfoundation/info_threefold/issues/69
