### ISSUE TITLE
Add more info about DIY + transparency about 3Node upcharge

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_farming#116]
Some people are starting to think we're just about selling nodes. We need to add more info about DIY farming as well as transparency about why there is an upcharge to buy a 3Node from ThreeFold. This information will make it more clear that yes we give the option to buy from us but it is certainly not the only options.

Places that will need an update:

- Farming Website (information added and button changes)
- Main Website (information added and button changes)
- Wiki (transparency around node upcharge)

Steps to get this completed:

- [ ] Decide what changes to make to farming website, main website, and wiki
- [ ] Get agreement from promo team
- [ ] Get agreement from stakeholders
- [ ] Create issue(s) for developers to execute changes

**Comment by Vilnite** [comment]
See on circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/issue/37
