### ISSUE TITLE
Logo fix in navbar for black mode

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_farming#12]
Logo invisible on black mode:

<img width="1440" alt="Screenshot 2020-12-10 at 13 14 21" src="https://user-images.githubusercontent.com/20182572/101771485-4d62a200-3aea-11eb-9cc7-ea6bfe95fe3a.png">

**Comment by samaradel** [comment]
It works please clear caches and try again
![image](https://user-images.githubusercontent.com/11662805/101780061-b522e800-3afe-11eb-808a-b24f3bc310ad.png)
