### ISSUE TITLE
Add new signup components

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_farming#24]
Please add these sign up components to farming website and webstack (let's place it on the bottom of participate page):
https://tailwindui.com/components/marketing/sections/cta-sections

- [x] with image on the right side
<img width="1415" alt="Screenshot 2020-12-28 at 12 43 41" src="https://user-images.githubusercontent.com/20182572/103208891-01916480-4902-11eb-9e04-6fe590ddc15d.png">

- [x] with image on the left side
<img width="1413" alt="Screenshot 2020-12-28 at 12 43 53" src="https://user-images.githubusercontent.com/20182572/103208913-0ce49000-4902-11eb-888d-e77a311b2fc9.png">

And make sure we have css (colors, buttons and fonts) matching overall website theme.

**Comment by ehab-hassan** [comment]
@samaradel components finished  but image cant load when put in md folder can u check please
![photo_٢٠٢٠-١٢-٢٩_١٨-٠٧-٥٣](https://user-images.githubusercontent.com/10484295/103302751-0c84eb80-4a0d-11eb-844c-13986e352928.jpg)

**Comment by samaradel** [comment]
Fixed
![image](https://user-images.githubusercontent.com/11662805/103357408-c89cef80-4abb-11eb-840a-5411519e1759.png)
