### ISSUE TITLE
Line breaks in header and cta components

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_farming#29]
See if we can have line breaks for sub-text in header and cta components:

<img width="1119" alt="Screenshot 2021-01-06 at 16 09 15" src="https://user-images.githubusercontent.com/20182572/103777449-8fbfc600-5039-11eb-8cba-59edfecceb2b.png">

**Comment by ehab-hassan** [comment]
@Vilnite I think the default line break is bette
![Threefold-Farming-Threefold-Farming](https://user-images.githubusercontent.com/10484295/104124377-4634eb00-5359-11eb-906a-b97728b28a70.png)
r to match with all section but I increase a bit please check when u can

**Comment by Vilnite** [comment]
yes, we don't want this.
What we want is this:

![example1](https://user-images.githubusercontent.com/20182572/104171349-2bbb4a00-540b-11eb-810c-da2db0441a82.png)

that we can place line break where we need it (after a sentence or two)

**Comment by Vilnite** [comment]
smth like this, only so it works:

<img width="1084" alt="Screenshot 2021-01-11 at 12 48 31" src="https://user-images.githubusercontent.com/20182572/104171457-5c9b7f00-540b-11eb-920b-78e7fe886d62.png">

**Comment by ehab-hassan** [comment]
ok ll delete the spaces made it

**Comment by Vilnite** [comment]
Now we have one header and one cta fixed on token page but rest of headers in whole website missing text.

<img width="1235" alt="Screenshot 2021-01-15 at 11 19 41" src="https://user-images.githubusercontent.com/20182572/104707033-895dd800-5724-11eb-8890-654c3a3c0a5a.png">
<img width="1203" alt="Screenshot 2021-01-15 at 11 20 00" src="https://user-images.githubusercontent.com/20182572/104707061-937fd680-5724-11eb-84ab-89c1b106eb1e.png">
<img width="1187" alt="Screenshot 2021-01-15 at 11 20 39" src="https://user-images.githubusercontent.com/20182572/104707085-9a0e4e00-5724-11eb-9280-8914f63d7c7b.png">
<img width="1203" alt="Screenshot 2021-01-15 at 11 21 17" src="https://user-images.githubusercontent.com/20182572/104707091-9c70a800-5724-11eb-8186-23526f01afbe.png">


Can you please fix this for all headers and cta's?

**Comment by ehab-hassan** [comment]
fixed
