### ISSUE TITLE
Update features and comparison component title size

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_farming#35]
Make sure feature component title size meets the resized cta and headers title size (#34)

right now feature titles are a bit too small comparing to other titles

<img width="1101" alt="Screenshot 2021-01-06 at 17 34 49" src="https://user-images.githubusercontent.com/20182572/103786873-9bb18500-5045-11eb-945f-3e4ab7239bd3.png">

**Comment by ehab-hassan** [comment]
I keep it as is while we resized all header , Cta , now all  have same seize to match with other size in one line
