### ISSUE TITLE
Add open source Google Analytics 

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_farming#37]
Need to add Google Analytics to our websites.
Please link with Sam for what and how the data will be handled.

**Comment by samtaggart** [comment]
@ehab-hassan just got in touch with me on this. We want to try to start using Matomo https://matomo.org/ (which was previously called Piwik) rather than Google Analytics. @VonSub can you help navigate this with Ehab?

**Comment by VonSub** [comment]
Correct, Matomo is the one I feel matches perfectly with us. Will see who can help installing this.

**Comment by VonSub** [comment]
Talking @ramezsaeed to see if OPS can handle this.

**Comment by VonSub** [comment]
Follow up here: https://github.com/threefoldtech/tf_operations/issues

**Comment by Hamdy** [comment]
I agree with https://matomo.org/ used to be called piwik 
was interesting to use 
but we need to integrate to our systems so may be our ops team can help in having an flist or so

**Comment by ehab-hassan** [comment]
script added at production and tested by @VonSub 
![photo_٢٠٢١-٠١-١٤_١٤-٠٦-٠٤](https://user-images.githubusercontent.com/10484295/104589553-ba7dd000-5672-11eb-969f-d23548df8c42.jpg)

**Comment by VonSub** [comment]
The code is added, and I can see it in the source. But we are still having trouble seeing the visits come in. I'm moving that discussion to the Support Ticket tho. This can be closed.
