### ISSUE TITLE
FARMING - Add Op-out dialog for Analytics Tracking

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/www_threefold_farming#40]
``` 
<iframe
        style="border: 0; height: 200px; width: 600px;"
        src="https://matomo.freeflowpages.com/index.php?module=CoreAdminHome&action=optOut&language=en&backgroundColor=d4d4d4&fontColor=545454&fontSize=14px&fontFamily=Helvetica"
        ></iframe>
```

**Comment by VonSub** [comment]
We need to add the code above for people to op-out of us tracking them.

**Comment by ehab-hassan** [comment]
![Threefold-Farming-Threefold-Farming (1)](https://user-images.githubusercontent.com/10484295/106385704-46655b00-63da-11eb-94d3-7d0cb6a35b05.png)
 
its keep showing there is no button support from matomo to hide when agree or disagree I use his script from matomo
<iframe
        style="border: 0; height: 200px; width: 600px;"
        src="https://analytics.threefold.io/index.php?module=CoreAdminHome&action=optOut&language=en&backgroundColor=2372b8&fontColor=ffffff&fontSize=&fontFamily=Ubuntu"
        ></iframe>

**Comment by VonSub** [comment]
so the iframe does not dissapear, whatever you do?

**Comment by ehab-hassan** [comment]
yes

**Comment by VonSub** [comment]
@ehab-hassan and @samaradel could you look into this: https://developer.matomo.org/guides/tracking-javascript-guide#optional-creating-a-custom-opt-out-form

**Comment by VonSub** [comment]
Any update here @ehab-hassan / @samaradel ?

**Comment by ehab-hassan** [comment]
nothing yet
this link  https://developer.matomo.org/guides/tracking-javascript-guide#optional-creating-a-custom-opt-out-form
show how to use script at opt-out same as script in body no button to hide the message box

**Comment by VonSub** [comment]
can't we create a box to hide it ourselves?

**Comment by Vilnite** [comment]
Added this to a new issue for adding analytics tracking for all websites: https://github.com/threefoldfoundation/home/issues/111
