### ISSUE TITLE
Why Page blogs should not open in a new tab

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_farming#47]
Currently clicking the blogs on the why page open in a new tab. Can we have them open in the same tab?

**Comment by Vilnite** [comment]
Still opens in new tab for me.

**Comment by samaradel** [comment]
![image](https://user-images.githubusercontent.com/11662805/105832063-285dbc00-5fd0-11eb-8d6d-59841cb04576.png)
No need to add a full link to point to link in the same website, ```/``` would be enough.
![image](https://user-images.githubusercontent.com/11662805/105832273-6b1f9400-5fd0-11eb-9ca5-89e53424f186.png)
