### ISSUE TITLE
Issues on Newsroom

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/www_threefold_farming#54]
Overview
- [x] Not displaying all content we have, feels like there should be a page 2 with older posts. (pagination issue?) Blog does have pages.
- [x] Filter navigation not working
- [x] Filter reset button not showing when in filtered view e.g. see: https://www2.farming.threefold.io/news/tags/marketplace/

Detail Pages
- [x] Make sure Author's name is displayed in the posts just like in the blog (besides author avatar)
- [x] Spacing between first line and image should be more

**Comment by Vilnite** [comment]
<img width="1245" alt="Screenshot 2021-02-01 at 13 31 32" src="https://user-images.githubusercontent.com/20182572/106453403-f2b64880-6491-11eb-8e0a-7293c924ce1b.png">

- [x] Can we please remove . (dot) that appears after date next to author image
- [x] Also space after main image is still not sufficient, let's make it at least as much as it is on top of the image
