### ISSUE TITLE
3Node page

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_threefold_farming#68]
intro

An electricity outlet, internet connection, and a 3Node are all you need to start earning. 

>>

All you need is an electricity outlet, internet connection, and a 3Node to start earning.

**Comment by Sacha96** [comment]
Meet Titan V2

No technical knowledge required. Comes pre-installed with Zero OS which automatically registers your node's capacity on the grid for people to use and helps to ensure security for your customers.

>>

No technical knowledge required. Comes pre-installed with Zero OS which automatically registers your node's capacity on the ThreeFold Grid.

___________

The team has designed this node with an eye on performance while ensuring an affordable entry point for all. The specs include: AMD Ryzen 5 3400G, 32 GB RAM, 480 GB SSD, and 1 TB HDD.

>>>

The team worked hard to design a powerful node while ensuring an affordable entry point. The specs include AMD Ryzen 5 3400G, 32 GB RAM, 480 GB SSD, and 1 TB HDD.

___________

The Titan V2 is no larger than a shoebox, making it a perfect fit for nearly any location. Its dimensions are 155 MM width by 155 MM height by 80 MM depth.

>>>

The Titan V2 is no larger than a shoebox, making it a perfect fit for all locations. Its dimensions are 155 MM wide, 155 MM high and 80 MM deep.

**Comment by Sacha96** [comment]
join the most advanced 'edge' >> 'peer-to-peer' network

**Comment by Sacha96** [comment]
Build the Internet of tomorrow

Simple plug & farm: All you need to get started is electricity, a network connection, and a 3Node. >>> .... started is a connection to electricity and network to connect your 3Node.

Offer Capacity: By connecting your 3Node, you provide decentralized storage and compute capacity for edge workloads. >>> .... you provide peer-to-peer .... to host humanity's edge workloads.

Earn Passive Income: Take part in the largest and most valuable economy in the world, the internet. >>> Take part in the most valuable and rapidly growing economy in the world, the Internet and cloud.

This is also for home page

**Comment by samtaggart** [comment]
Scott recommended that we change MM to mm for the dimensions as well.

And add (about 6x6x3 inches).
