### ISSUE TITLE
token page

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_threefold_farming#69]
Token features

A Real Utility:  1 TFT represents a unit of Storage (SU) and/or Compute (CU) on the ThreeFold Grid - the peer-to-peer alternative to the current internet and cloud. >>> ..... - an efficient, secure and peer-to-peer alternative to....

**Comment by samtaggart** [comment]
Also from Scott:

Not satisfied with payment system? >> systems

TFT is having more and more use-cases. >> continues to have
