### ISSUE TITLE
FARMING - See if we can get more balanced spacing on Tech Page

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/www_threefold_farming#70]
There's one very specific whitespace that keeps bothering us.
We're aware it might impact other components, but can wel look at making it more balanced?
As it seems the title is part of the section above rather than the section below.

<img width="1179" alt="Screenshot 2021-02-08 at 14 13 56" src="https://user-images.githubusercontent.com/29431263/107238187-d8e3ab00-6a27-11eb-8fba-f5bdc537901d.png">

**Comment by ehab-hassan** [comment]
I add some space at top so it show that is related to below section but cant control it too much while it is separated component and may affect all website
