### ISSUE TITLE
FARMING - Implement Newsletter onboarding. 

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/www_threefold_farming#74]
We want to funnel more people to our newsletter as we're gearing up more communication strategies.

- [x] Determine places to put the buttons (@VonSub)
- [x] Implement the Mailerlite pop-up (@ehab-hassan / @samaradel )
- [x] Review privacy policy to make sure email collecting is mentioned (@VonSub)
- [x] Determine which list we onboard people into (@VonSub)

**Comment by ehab-hassan** [comment]
@VonSub do we have account at Mailerlite?

**Comment by VonSub** [comment]
Yes, collecting info as we speak brother

**Comment by VonSub** [comment]
Insert the following snippet of JavaScript on every page of your website right before the closing </head> tag.

Please note: You only need to add this snippet once, even if you plan to have a few different forms. There is no need to insert this JavaScript snippet if you already have it on your website.

```
<!-- MailerLite Universal -->
<script>
(function(m,a,i,l,e,r){ m['MailerLiteObject']=e;function f(){
var c={ a:arguments,q:[]};var r=this.push(c);return "number"!=typeof r?r:f.bind(c.q);}
f.q=f.q||[];m[e]=m[e]||f.bind(f.q);m[e].q=m[e].q||f.q;r=a.createElement(i);
var _=a.getElementsByTagName(i)[0];r.async=1;r.src=l+'?v'+(~~(new Date().getTime()/1000000));
_.parentNode.insertBefore(r,_);})(window, document, 'script', 'https://static.mailerlite.com/js/universal.js', 'ml');

var ml_account = ml('accounts', '1778010', 'x2d3d9f8n1', 'load');
</script>
<!-- End MailerLite Universal -->

```

**Comment by VonSub** [comment]
If you would like to open a pop-up on link click, please use the following example.

```
<a href="javascript:;" onclick="ml_account('webforms', '3562741', 'n7q9l7', 'show')">
  Click here to show popup
</a>
```

**Comment by VonSub** [comment]
For placement we defined 3 places:

An "envelope" can be added to the navbar and footer

![image](https://user-images.githubusercontent.com/29431263/108040765-ff17d500-703d-11eb-9619-d445fefdfd0f.png)
![image](https://user-images.githubusercontent.com/29431263/108040734-f6270380-703d-11eb-8933-7c20b4968f6a.png)

In the Homepage we would like another section like the one that's below:

Title: Stay up to Date
Subtitle: ThreeFold is a fast-paced project, and we understand at times it's hard to keep up. To make that easier you can always sign up for our newsletter to get all the latest updates in bite-sized chunks in your inbox.
Button: Join Newsletter

![image](https://user-images.githubusercontent.com/29431263/108040982-43a37080-703e-11eb-9583-43826ffcc1b4.png)

**Comment by VonSub** [comment]
@ehab-hassan let me know if there's any questions brother

**Comment by VonSub** [comment]
tested locally with Ehab. it works. now to review the privacy policy.
