### ISSUE TITLE
FARMING - Feature impressum on the page

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/www_threefold_farming#75]
We legally are obliged to feature an impressum on our pages.

- [x] Check what entity owns farming page (TFtech or TFfoundation) @VonSub 
- [ ] Gather impressum info for entity @VonSub 
- [ ] Get it into the wiki and link from the footer

**Comment by VonSub** [comment]
Waiting for legal info from Raj to complete the impressum. Blocked for now.

**Comment by samtaggart** [comment]
Impressums needed for all pages. See Issue #132 on Home repo
