### ISSUE TITLE
FARMING - mobile view navbar fix

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_farming#77]
Navbar doesn't collapse when select pages:
![IMAGE 2021-02-17 16:11:02](https://user-images.githubusercontent.com/20182572/108216090-bb56c580-713a-11eb-9fb0-44ed929ec091.jpg)

**Comment by ehab-hassan** [comment]
fixed at staging
Note: I remove close of menu at mobile if click a any part of page that make conflict with filter menu
u can close menu from (x) at top
