### ISSUE TITLE
FARMING - Price is limited to 10ct

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_threefold_farming#84]
<img width="873" alt="Screenshot 2021-03-20 at 09 20 10" src="https://user-images.githubusercontent.com/61866569/111859900-97ff8000-895d-11eb-8b1d-292e87ff8973.png">
The current farming website states that 
"The currency of the peer-to-peer Internet, the ThreeFold Grid. Current value of TFT on ThreeFold Grid = $0.10"
As the price will soon be higher then 10ct, we need to prepare for an alternative wording or better update already.

**Comment by Sacha96** [comment]
What is the solution you propose @maximilianrang ? Remove .10?

**Comment by maximilianrang** [comment]
Yes because even when we say it is a always a minimum of .10, this will mention a low price of TFT. I would recommend to remove.

**Comment by Sacha96** [comment]
perfect will be done today once latest publishtools is pushed.
