### ISSUE TITLE
Move Grid block from 3Node to Tech (Grid) page

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_threefold_farming#90]

**Comment by Vilnite** [comment]
Did you mean:
This?

<img width="1213" alt="Screenshot 2021-04-13 at 12 13 43" src="https://user-images.githubusercontent.com/20182572/114528742-f31d4d80-9c51-11eb-9929-ecd9265a4f46.png">

Over somewhere here?

<img width="1440" alt="Screenshot 2021-04-13 at 12 14 38" src="https://user-images.githubusercontent.com/20182572/114528757-f6183e00-9c51-11eb-8aab-f4396052f7d2.png">

**Comment by Sacha96** [comment]
Perfect thanks 👍
