### ISSUE TITLE
ADD Carbon Neutral block

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_threefold_farming#91]
Create block that covers carbon neutral approach:

Title: First Carbon Neutral Grid
Text: 

ThreeFold’s peer-to-peer nature brings considerable energy efficiencies as compared to current solutions. 

The remaining carbon footprint of the grid will be converted into carbon credits and invested in planet positive projects to enable the world’s first carbon neutral grid.

**Comment by Vilnite** [comment]
Issue exactly like this already exist: https://github.com/threefoldfoundation/www_threefold_cloud/issues/24

**Comment by Sacha96** [comment]
yeah but its a different website different file

**Comment by Sacha96** [comment]
![Farming - Earth Friendly Block](https://user-images.githubusercontent.com/54844940/115037015-51eefb00-9ece-11eb-9fec-b54c9997e6ce.png)

**Comment by Sacha96** [comment]
add after peer-to-peer grid component on main page
